# Stage 1 - Composer
FROM composer:1.9 AS composer

# Stage 2 - Email microservice Publisher
FROM php:7.3-fpm

# Install Dependencies
RUN apt-get update && apt-get install -y \
    git \
    libzip-dev \
    zip \
    unzip \
    libpq-dev \
    librabbitmq-dev \
    libssh-dev && \
    pecl install xdebug amqp && \
    docker-php-ext-enable xdebug

# Install PHP extensions
RUN docker-php-ext-configure zip --with-libzip
RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
RUN docker-php-ext-install pdo pdo_mysql pdo_pgsql pgsql zip bcmath sockets
RUN docker-php-ext-enable amqp

# Application Workdir
WORKDIR /var/www/html/email_microservice

# Copy Laravel and Composer files
COPY database/ database/
COPY composer.json composer.json
COPY composer.lock composer.lock

# Copy Composer binary
COPY --from=composer /usr/bin/composer /usr/bin/composer

# Install Composer Dependencies
RUN composer install \
    --no-interaction \
    --no-plugins \
    --no-scripts \
    --prefer-dist

# Copy project files
COPY . /var/www/html/email_microservice

# Copy XDebug file
COPY ./infrastructure/xdebug/xdebug.ini /usr/local/etc/php7.3/conf.d/

# Update directory permissions
RUN chown -R www-data:www-data \
    /var/www/html/email_microservice/storage \
    /var/www/html/email_microservice/bootstrap/cache

# Generate Laravel Key
RUN php artisan key:generate

# Clean Laravel Config
RUN php artisan config:clear
RUN php artisan clear-compiled

# Add Wait script
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.6.0/wait /wait
RUN chmod +x /wait

# Port to expose
EXPOSE 9000

# Run app server
CMD /wait && php-fpm
